services:
  couchbase:
    image: couchbase:enterprise
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: ${SPRING_COUCHBASE_USERNAME}
      COUCHBASE_ADMINISTRATOR_PASSWORD: ${SPRING_COUCHBASE_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/ui/index.html"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      DB_CONN_STR: "couchbase://couchbase:11210"
      DB_BUCKET_NAME: "WebCompBuilder"
      DB_USERNAME: "couch-admin"
      DB_PASSWORD: "[changed]" #${DB_PASSWORD}

volumes:
  couchbase_data: